---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: "{{ bspwm_packages }}"
    state: latest
    update_cache: yes

- name: Create bspwm config file
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    src: bspwm

- name: Add wallpapers
  become: yes
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id}}"
    mode: 0644
    owner: "{{ user_id}}"
    src: "feh"
