---

- name: Ensure required packages are removed
  become: yes
  pacman:
    extra_args: --recursive
    name: "{{ bspwm_packages }}"
    state: absent

- name: Ensure config directories are removed
  file:
    path: "{{ user_home }}/.config/{{ item }}"
    state: absent
  loop:
    - bspwm
    - feh
