---

cli_utilities_packages:
  - alsa-utils
  - fzf
  - htop
  - iotop
  - jq
  - lastpass-cli
  - man-db
  - man-pages
  - ncdu
  - nmap
  - ranger
  - strace
  - tig
  - unrar
  - unzip
  - wget
  - xclip
  - xdg-utils
