---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: "{{ dunst_packages }}"
    state: latest
    update_cache: yes

- name: Create config directory
  file:
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/dunst"
    state: directory

- name: Create dunstrc config file
  template:
    dest: "{{ user_home }}/.config/dunst/dunstrc"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: "dunstrc.j2"
