---

- name: Ensure required packages are removed
  become: yes
  pacman:
    extra_args: --recursive
    name: "{{ polybar_packages }}"
    state: absent

- name: Ensure config directory is removed
  file:
    path: "{{ user_home }}/.config/polybar"
    state: absent
