---

- name: Ensure lastpass is installed
  become: yes
  pacman:
    name: "{{ lastpass_package_name }}"
    state: latest
    update_cache: yes

- name: Create lpass directory
  file:
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.local/share/lpass"
    state: directory
