---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: "{{ zathura_packages }}"
    state: latest
    update_cache: yes

- name: Create config directory
  file:
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/zathura"
    state: directory

- name: Create zathura config file
  template:
    dest: "{{ user_home }}/.config/zathura/zathurarc"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: 'zathurarc.j2'
