---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: "{{ zathura_packages }}"
    state: latest
    update_cache: yes

- name: Copy config files
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    src: zathura

- name: Create symbolic link to theme
  file:
    dest: "{{ user_home }}/.config/zathura/themes/default"
    group: "{{ user_id }}"
    owner: "{{ user_id }}"
    src: "{{ user_home }}/.config/zathura/themes/{{ theme }}"
    state: link
