#!/bin/sh

command_exists() {
        command -v "$@" >/dev/null 2>&1
}

command_exists picom && picom &
command_exists polybar && polybar top &

# Fix cursor
xsetroot -cursor_name left_ptr

# Toggle language with win + space
setxkbmap us,es -option 'grp:win_space_toggle'

feh --no-fehbg --bg-fill ~/.config/feh/wallpapers/gradient.png &

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0

bspc config focus_follows_pointer true
bspc config top_padding 30
bspc config window_gap 15
