---

- name: Ensure neofetch is removed
  become: yes
  pacman:
    extra_args: --recursive
    name: "{{ neofetch_package_name }}"
    state: absent

- name: Ensure config directory is removed
  file:
    path: "{{ user_home }}/.config/neofetch"
    state: absent
