---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: "{{ neovim_package_name }}"
    state: latest
    update_cache: yes

- name: Create neovim config file
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: nvim

- name: Ensure autoload path exist
  file:
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.local/share/nvim/site/autoload"
    state: directory

- name: Download vim-plug
  get_url:
    dest: "{{ user_home }}/.local/share/nvim/site/autoload/plug.vim"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
