---

- name: Ensure required packages are removed
  become: yes
  pacman:
    extra_args: --recursive
    name: "{{ neovim_package_name }}"
    state: absent

- name: Ensure config directory is removed
  file:
    path: "{{ user_home }}/.config/nvim"
    state: absent
