---

- name: Ensure required packages are removed
  become: yes
  pacman:
    extra_args: --recursive
    name: "{{ neovim_package_name }}"
    state: absent

- name: Ensure config directories are removed
  file:
    path: "{{ user_home }}/{{ item }}"
    state: absent
  loop:
    - ".config/nvim"
    - ".local/share/nvim/site/autoload"
